---
- name: Provisionner une VM dans OpenShift Virtualization (Namespace mchoura)
  hosts: localhost
  connection: local
  vars:
    # Vos variables spécifiques
    vm_namespace: "mchoura" 
    vm_name: "newvm-test"
    vm_network_name: "mchoura/vlan-2005" 
    vm_user: "missa" 
    vm_password: "missou"
    vm_ip: "172.16.5.20/24" # <-- Nouvelle variable pour l'IP statique

  tasks:
    - name: Déployer la VirtualMachine via l'API KubeVirt
      kubernetes.core.k8s:
        state: present
        verify_ssl: no # À passer à 'yes' en production si vous avez des certificats valides
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name }}"
            namespace: "{{ vm_namespace }}"
          spec:
            running: true
            template:
              metadata:
                labels:
                  app: test-aap-vlan
              spec:
                domain:
                  resources:
                    requests:
                      memory: "1Gi"
                  cpu:
                    cores: 1
                  devices:
                    disks:
                      - name: os-disk
                        disk:
                          bus: virtio
                      - name: cloudinitdisk
                        disk:
                          bus: virtio
                    interfaces:
                      # Interface 1 (eth0) : Réseau par défaut
                      - name: default
                        masquerade: {}
                      # Interface 2 (eth1) : Réseau VLAN
                      - name: vlan-interface
                        bridge: {}
                networks:
                  - name: default
                    pod: {}
                  - name: vlan-interface
                    multus:
                      networkName: "{{ vm_network_name }}"
                volumes:
                  - name: os-disk
                    containerDisk:
                      image: quay.io/containerdisks/fedora:latest
                  - name: cloudinitdisk
                    cloudInitNoCloud:
                      # --- 1. Identifiants de connexion ---
                      userData: |
                        #cloud-config
                        user: {{ vm_user }}
                        password: {{ vm_password }}
                        chpasswd: { expire: False }
                        ssh_pwauth: True
                      # --- 2. Configuration IP Statique ---
                      networkData: |
                        version: 2
                        ethernets:
                          eth1:
                            dhcp4: false
                            addresses:
                              - {{ vm_ip }}
