- hosts: localhost
  connection: local
  vars:
    vm_namespace: "mchoura" 
    vm_name: "newvm-test"
    vm_network_name: "mchoura/vlan-2005" 
    vm_user: "rhel"               
    vm_password: "missou"         
    vm_ip: "172.16.5.20/24"       
    vm_gateway: "172.16.5.1"
    macAddress: '02:2c:5a:00:00:00'

  tasks:
    - name: Déployer la VirtualMachine via l'API KubeVirt
      kubernetes.core.k8s:
        state: present
        verify_ssl: no 
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name }}"
            namespace: "{{ vm_namespace }}"
          spec:
            running: true
            instancetype:
              name: u1.medium
            preference:
              name: fedora
            template:
              metadata:
                labels:
                  app: test-aap-vlan
              spec:
                domain:
                  devices:
                    interfaces:
                      - name: vlan-interface
                        bridge: {}
                        model: virtio
                        macAddress: "{{ macAddress  }}"
                    disks:
                      - name: containerdisk
                        disk:
                          bus: virtio
                      - name: cloudinit
                        disk:
                          bus: virtio
                networks:
                  - name: vlan-interface
                    multus:
                      networkName: "{{ vm_network_name }}"
                volumes:
                  - name: containerdisk
                    containerDisk:
                      image: quay.io/containerdisks/fedora:latest
                  - name: cloudinit
                    cloudInitNoCloud:
                      userData: |
                        #cloud-config
                        user: {{ vm_user }}
                        password: {{ vm_password }}
                        chpasswd: { expire: False }
                        ssh_pwauth: True
                      
                      networkData: |
                        version: 2
                        ethernets:
                          carte_vlan:
                            match:
                              macaddress: {{ macAddress }}
                            dhcp4: false
                            addresses:
                              - {{ vm_ip }}
                            routes:
                              - to: 0.0.0.0/0
                                via: {{ vm_gateway }}
