---
- name: Provisionner une VM dans OpenShift Virtualization (Namespace mchoura)
  hosts: localhost
  connection: local
  vars:
    # Vos variables spécifiques
    vm_namespace: "mchoura" 
    vm_name: "newvm-test"
    vm_network_name: "mchoura/vlan-2005" 
    
    vm_user: "rhel"              
    vm_password: "missou"         
    vm_ip: "172.16.5.20/24"      
    vm_gateway: "172.16.5.1" 

  tasks:
    - name: Déployer la VirtualMachine via l'API KubeVirt
      kubernetes.core.k8s:
        state: present
        verify_ssl: no 
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name }}"
            namespace: "{{ vm_namespace }}"
          spec:
            running: true
            template:
              metadata:
                labels:
                  app: test-aap-vlan
              spec:
                domain:
                  resources:
                    requests:
                      memory: "1Gi"
                  cpu:
                    cores: 1
                  devices:
                    disks:
                      - name: os-disk
                        disk:
                          bus: virtio
                      - name: cloudinitdisk
                        disk:
                          bus: virtio
                    interfaces:
                      - name: vlan-interface
                        bridge: {}
                        model: virtio
                networks:
                  - name: vlan-interface
                    multus:
                      networkName: "{{ vm_network_name }}"
                volumes:
                  - name: os-disk
                    containerDisk:
                      image: quay.io/containerdisks/fedora:latest
                  - name: cloudinitdisk
                    cloudInitNoCloud:
                      userData: |
                        #cloud-config
                        user: {{ vm_user }}
                        password: {{ vm_password }}
                        chpasswd: { expire: False }
                        ssh_pwauth: True
                      
                      networkData: |
                        version: 2
                        ethernets:
                          enp1s0:            
                            dhcp4: false
                            addresses:
                              - {{ vm_ip }}
                            gateway4: {{ vm_gateway }}  
